name: Verify

on:
  push:
    tags-ignore:
      - "**"
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - uses: ./.github/actions/setup

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          args: --new-from-rev=HEAD~ --timeout=10m

      - name: Verify docs
        run: make verify-docs
